create table if not exists currencies (
    id       int primary key generated by default as identity,
    code     varchar(10) unique not null,
    name     varchar(100) not null,
    sign     varchar(5) not null
    );

create table if not exists exchange_rates (
    id int primary key generated by default as identity,
    baseCurrency int not null references currencies(id),
    targetCurrency int not null references currencies(id),
    rate decimal not null
    );